/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProductThinkingRouteImport } from './routes/product-thinking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as EssaysAiProblemsRouteImport } from './routes/essays.ai-problems'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductThinkingRoute = ProductThinkingRouteImport.update({
  id: '/product-thinking',
  path: '/product-thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const EssaysAiProblemsRoute = EssaysAiProblemsRouteImport.update({
  id: '/essays/ai-problems',
  path: '/essays/ai-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/essays/ai-problems'
    | '/case-studies/'
    | '/api/public/contact-submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/essays/ai-problems'
    | '/case-studies'
    | '/api/public/contact-submit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/essays/ai-problems'
    | '/case-studies/'
    | '/api/public/contact-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProductThinkingRoute: typeof ProductThinkingRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EssaysAiProblemsRoute: typeof EssaysAiProblemsRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-thinking': {
      id: '/product-thinking'
      path: '/product-thinking'
      fullPath: '/product-thinking'
      preLoaderRoute: typeof ProductThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/essays/ai-problems': {
      id: '/essays/ai-problems'
      path: '/essays/ai-problems'
      fullPath: '/essays/ai-problems'
      preLoaderRoute: typeof EssaysAiProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  ProductThinkingRoute: ProductThinkingRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EssaysAiProblemsRoute: EssaysAiProblemsRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
