/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProductThinkingRouteImport } from './routes/product-thinking'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as WritingProductDiscoverySoftwareEngineeringRouteImport } from './routes/writing.product-discovery-software-engineering'
import { Route as EssaysAiProblemsRouteImport } from './routes/essays.ai-problems'
import { Route as CaseStudiesOnlyfyTalentPoolRouteImport } from './routes/case-studies.onlyfy-talent-pool'
import { Route as CaseStudiesNotificationsRouteImport } from './routes/case-studies.notifications'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductThinkingRoute = ProductThinkingRouteImport.update({
  id: '/product-thinking',
  path: '/product-thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const WritingProductDiscoverySoftwareEngineeringRoute =
  WritingProductDiscoverySoftwareEngineeringRouteImport.update({
    id: '/writing/product-discovery-software-engineering',
    path: '/writing/product-discovery-software-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const EssaysAiProblemsRoute = EssaysAiProblemsRouteImport.update({
  id: '/essays/ai-problems',
  path: '/essays/ai-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesOnlyfyTalentPoolRoute =
  CaseStudiesOnlyfyTalentPoolRouteImport.update({
    id: '/onlyfy-talent-pool',
    path: '/onlyfy-talent-pool',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesNotificationsRoute =
  CaseStudiesNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/notifications': typeof CaseStudiesNotificationsRoute
  '/case-studies/onlyfy-talent-pool': typeof CaseStudiesOnlyfyTalentPoolRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/writing/product-discovery-software-engineering': typeof WritingProductDiscoverySoftwareEngineeringRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/notifications': typeof CaseStudiesNotificationsRoute
  '/case-studies/onlyfy-talent-pool': typeof CaseStudiesOnlyfyTalentPoolRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/writing/product-discovery-software-engineering': typeof WritingProductDiscoverySoftwareEngineeringRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/writing': typeof WritingIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/product-thinking': typeof ProductThinkingRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/notifications': typeof CaseStudiesNotificationsRoute
  '/case-studies/onlyfy-talent-pool': typeof CaseStudiesOnlyfyTalentPoolRoute
  '/essays/ai-problems': typeof EssaysAiProblemsRoute
  '/writing/product-discovery-software-engineering': typeof WritingProductDiscoverySoftwareEngineeringRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/work'
    | '/case-studies/$slug'
    | '/case-studies/notifications'
    | '/case-studies/onlyfy-talent-pool'
    | '/essays/ai-problems'
    | '/writing/product-discovery-software-engineering'
    | '/case-studies/'
    | '/writing/'
    | '/api/public/contact-submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/work'
    | '/case-studies/$slug'
    | '/case-studies/notifications'
    | '/case-studies/onlyfy-talent-pool'
    | '/essays/ai-problems'
    | '/writing/product-discovery-software-engineering'
    | '/case-studies'
    | '/writing'
    | '/api/public/contact-submit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/product-thinking'
    | '/resume'
    | '/sitemap.xml'
    | '/work'
    | '/case-studies/$slug'
    | '/case-studies/notifications'
    | '/case-studies/onlyfy-talent-pool'
    | '/essays/ai-problems'
    | '/writing/product-discovery-software-engineering'
    | '/case-studies/'
    | '/writing/'
    | '/api/public/contact-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ProductThinkingRoute: typeof ProductThinkingRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  EssaysAiProblemsRoute: typeof EssaysAiProblemsRoute
  WritingProductDiscoverySoftwareEngineeringRoute: typeof WritingProductDiscoverySoftwareEngineeringRoute
  WritingIndexRoute: typeof WritingIndexRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-thinking': {
      id: '/product-thinking'
      path: '/product-thinking'
      fullPath: '/product-thinking'
      preLoaderRoute: typeof ProductThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/writing/product-discovery-software-engineering': {
      id: '/writing/product-discovery-software-engineering'
      path: '/writing/product-discovery-software-engineering'
      fullPath: '/writing/product-discovery-software-engineering'
      preLoaderRoute: typeof WritingProductDiscoverySoftwareEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/ai-problems': {
      id: '/essays/ai-problems'
      path: '/essays/ai-problems'
      fullPath: '/essays/ai-problems'
      preLoaderRoute: typeof EssaysAiProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/onlyfy-talent-pool': {
      id: '/case-studies/onlyfy-talent-pool'
      path: '/onlyfy-talent-pool'
      fullPath: '/case-studies/onlyfy-talent-pool'
      preLoaderRoute: typeof CaseStudiesOnlyfyTalentPoolRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/notifications': {
      id: '/case-studies/notifications'
      path: '/notifications'
      fullPath: '/case-studies/notifications'
      preLoaderRoute: typeof CaseStudiesNotificationsRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesNotificationsRoute: typeof CaseStudiesNotificationsRoute
  CaseStudiesOnlyfyTalentPoolRoute: typeof CaseStudiesOnlyfyTalentPoolRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesNotificationsRoute: CaseStudiesNotificationsRoute,
  CaseStudiesOnlyfyTalentPoolRoute: CaseStudiesOnlyfyTalentPoolRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ProductThinkingRoute: ProductThinkingRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  EssaysAiProblemsRoute: EssaysAiProblemsRoute,
  WritingProductDiscoverySoftwareEngineeringRoute:
    WritingProductDiscoverySoftwareEngineeringRoute,
  WritingIndexRoute: WritingIndexRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
